name: "master: build, upload, draft release"

on:
  push:
    branches:
      - master
    paths-ignore:
      - ".gitignore"
  pull_request:
    branches:
      - master
    paths-ignore:
      - ".gitignore"
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: write

jobs:
  build:
    runs-on: macos-latest
    environment: Patch AutoBuildRelease
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install Procursus
        uses: dhinakg/procursus-action@main
        with:
          packages: ldid trustcache findutils coreutils sed make

      - name: Install THEOS (without SDKs)
        run: |
          set -x
          export BASEDIR="$(pwd)"
          export THEOS="${BASEDIR}/theos"
          mkdir -p $THEOS
          curl -fsSL https://raw.githubusercontent.com/theos/theos/master/bin/install-theos >> install-theos.sh
          gsed -E "/^\s*get_theos\s*$/,+1 s/^(\s*)(get_sdks)\s*$/\1mkdir -p \${THEOS}\/sdks\n\1touch \${THEOS}\/sdks\/sdk\n\1\2/g" -i install-theos.sh
          bash install-theos.sh
          cd $BASEDIR

      - name: Set Environment Variables
        run: |
         T8=$(TZ=UTC-8 date +'%Y%m%d_%H%M%S')
         TS=$(date -j -f "%Y%m%d_%H%M%S" "${T8}" +%s)
         SHASH=$(git rev-parse --short HEAD)
         echo "Git commit log since last tag:" >> ./release.md
         echo "\`\`\`" >> ./release.md
         git log --graph --pretty=format:'%h - %s <%an>' --abbrev-commit $(git describe --tags --abbrev=0).. >> ./release.md
         echo "" >> ./release.md
         echo "\`\`\`" >> ./release.md
         echo "ctime=${T8}" >> $GITHUB_ENV
         echo "ctimestamp=${TS}" >> $GITHUB_ENV
         echo "shorthash=${SHASH}" >> $GITHUB_ENV

      - name: Print Environment Variables
        run: |
         echo ${{ env.ctime }}
         echo ${{ env.ctimestamp }}
         echo ${{ env.shorthash }}
         cat ./release.md

      - name: Build
        run: |
          set -x
          sudo security import Exploits/fastPath/arm.pfx -k /Library/Keychains/System.keychain -P password -A
          export BASEDIR="$(pwd)"
          export THEOS="${BASEDIR}/theos"
          gmake
          mv Dopamine/Dopamine.tipa Dopamine_${{ env.shorthash }}_${{ env.ctime }}.tipa

      - name: Upload Artifact
        uses: actions/upload-artifact@v2.3.1
        with:
          name: Dopamine tipa
          path: |
            ${{ github.workspace }}/Dopamine_${{ env.shorthash }}_${{ env.ctime }}.tipa

      - name: Pre-release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: "0000_master_${{ env.ctime }}"
          name: "Dopamine: ${{ env.shorthash }}_${{ env.ctime }}"
          body_path: ./release.md
          draft: true
          prerelease: true
          token: ${{ secrets.CUSTOM_GITHUB_TOKEN }}
          files: |
           *.tipa
